title: TyGAMES
tagline: "Coopérative bretonne d'édition et distribution de jeux vidéo"
description: "Un autre modèle d'édition est possible : coopératif, transparent, résilient. Rejoignez-nous !"
image: /assets/img/og.png
logo: /assets/img/logo_white.png
baseurl: ""
url: "https://ty.games"
lang: fr
email: hello@ty.games
location: Rennes, Bretagne

social:
  bluesky: https://bsky.app/profile/ty.games
  mastodon: 
  instagram: 
  youtube: 
  discord: https://discord.gg/tygames

collections:
  games:
    output: true
    permalink: /games/:name/

defaults:
  - scope:
      path: ""
      type: games
    values:
      layout: game
      lang: fr

  - scope:
      path: "en"
    values:
      lang: en

plugins:
  - jekyll-seo-tag

exclude:
  - node_modules/
  - package.json
  - package-lock.json
  - tailwind.config.js
  - assets/css/input.css
  - Gemfile
  - Gemfile.lock
  - vendor/
  - .github/
  - README.md
