title: TyGAMES
tagline: "Coopérative d'édition et distribution de jeux vidéo"
description: "Un autre modèle d'édition est possible : coopératif, transparent, résilient. Rejoignez-nous !"
image: /assets/img/og.png
logo: /assets/img/logo_white.png
baseurl: ""
url: "https://ty.games"
lang: fr
email: hello@ty.games
location: Rennes, Bretagne

social:
  bluesky: https://bsky.app/profile/ty.games
  mastodon:
  instagram:
  youtube: https://www.youtube.com/@TyGAMES-Publisher
  discord: https://discord.gg/RqzHAtpbXZ
  substack: https://tygames.substack.com
  linkedin: https://www.linkedin.com/company/tygames

stores:
  steam: https://store.steampowered.com/publisher/tygames
  gog: https://www.gog.com/fr/games?publishers=tygames
  epic: 
  humble: https://www.humblebundle.com/store/search?publisher=TyGAMES
  app_store: https://apps.apple.com/fr/developer/tygames/id1663858681
  google_play: https://play.google.com/store/apps/dev?id=5075684495718628174
  nintendo: https://eshop-prices.com/games?publisher=TyGAMES
  playstation: https://store.playstation.com/en-us/concept/10013114
  xbox: 

collections:
  games:
    output: true
    permalink: /games/:slug/

defaults:
  - scope:
      path: ""
      type: games
    values:
      layout: game
      lang: fr

  - scope:
      path: "en"
    values:
      lang: en

plugins:
  - jekyll-seo-tag

exclude:
  - node_modules/
  - package.json
  - package-lock.json
  - tailwind.config.js
  - assets/css/input.css
  - Gemfile
  - Gemfile.lock
  - vendor/
  - .github/
  - README.md
